select * from qa_users;
select username, user_id from qa_users;
select user_id from qa_users;
select username from qa_users;
select email from qa_users;
select username, email from qa_users;
select user_id, username, email, created_on from qa_users;
select username from qa_users where password='12333';
select username from qa_users where created_on='2021-03-26 00:00:00';
select username from qa_users where username like 'Anna%';
select username from qa_users where username like '%8';
select username from qa_users where username like '%a';
select username from qa_users where created_on='2021-07-12 00:00:00';
select username from qa_users where created_on='2021-07-12 00:00:00' and password='1m313';
select username from qa_users where created_on='2021-07-12' and username like'%Andrey%';
select username from qa_users where created_on='2021-07-12 00:00:00' and username like '%8';
select username from qa_users where user_id=10;
select username from qa_users where user_id=53;
select username from qa_users where user_id>40;
select username from qa_users where user_id<30;
select username from qa_users where user_id<27 or user_id>88;
select username from qa_users where user_id<=37;
select username from qa_users where user_id>=37;
select username from qa_users where user_id>80 and user_id<90;
select username from qa_users where user_id between 80 and 90;
select username from qa_users where password in ('12333', '1m313', '123313');
select username from qa_users where created_on in ('2020-10-03 00:00:00', '2021-05-19 00:00:00', '2021-03-26 00:00:00');
select min(user_id) from qa_users;
select max(user_id) from qa_users;
select count(user_id) from qa_users;
select user_id, username, created_on from qa_users order by created_on;
select user_id, username, created_on from qa_users order by created_on desc;